repos:
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.5.0
  #   hooks:
  #     - id: check-added-large-files

  - repo: local
    hooks:
      - id: prevent-push-to-main
        name: Prevent push to main
        entry: scripts/prevent_push_main.sh
        language: system
        pass_filenames: false
        stages: [pre-push]

  # # Optional: check Python code in ml/
  # - repo: https://github.com/psf/black
  #   rev: 24.3.0
  #   hooks:
  #     - id: black
  #       files: ^ml/

  # # Optional: check JS code in frontend/backend
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v3.2.5
  #   hooks:
  #     - id: prettier
  #       files: ^(frontend|backend)/.*\.(js|jsx|ts|tsx|json|css|html|md)$
