services:
  ml-api-prod:
    image: khanhlinh02/ml-service:latest
    container_name: ml-api-prod
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    restart: unless-stopped
    networks:
      - backend-network-prod
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/health')\" || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  backend-network-prod:
    driver: bridge
    external: true
    name: backend-network-prod
